blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/knakanishi/uv-starter/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://knakanishi.github.io/uv-starter/
    about: Read the project documentation